#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2014 OpenWrt.org

START=100
STOP=100


USE_PROCD=1

NAME=luci-app-openfrp-server


stop () {
	echo "openfrp-server stop. $date" >> ${NAME}.log
	service_stop $PROG
}


start () {
	echo "openfrp-server ${NAME} start. $date" >> ${NAME}.log
	start_service
}


restart () {
	echo "restart ${NAME} openfrp-server $date " >> ${NAME}.log
	stop 
	start
}


reload_service() {
	local rv=0
	ubus call "${NAME}" reload || rv=1
	restart
	return $rv
}